
[theme]
base="light"
primaryColor="#FF0000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#999999"
textColor="#000000"
font="serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 8501





